"""Add band_venue Association Table

Revision ID: 0a997830c57d
Revises: 02080f531eb5
Create Date: 2024-09-14 10:55:56.763338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a997830c57d'
down_revision: Union[str, None] = '02080f531eb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('band_venues',
    sa.Column('band_id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['band_id'], ['bands.id'], name=op.f('fk_band_venues_band_id_bands')),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], name=op.f('fk_band_venues_venue_id_venues')),
    sa.PrimaryKeyConstraint('band_id', 'venue_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('band_venues')
    # ### end Alembic commands ###
